return {
    -- Example items; replace names with your ox_inventory item names.
    -- amount = how much stress to remove (0-100 scale). Values <= 0 will fully clear stress.

    -- Drinks and soft beverages (small relief)
    water = { amount = 5 },
    water_50cl = { amount = 6 },
    cola = { amount = 8 },
    sprunk = { amount = 8 },
    ecola = { amount = 8 },
    ecola_small = { amount = 6 },
    ecola_big = { amount = 10 },
    sprunk_big = { amount = 10 },
    apple_juice = { amount = 10 },
    orango_tang = { amount = 10 },
    junk = { amount = 10 },
 
    -- Coffee and warm drinks (medium relief)
    coffee = { amount = 18 },
	["cc-coffeejelly"] = { amount = 20 },
	cb_coffee = { amount = 22 },
    latte_cappuccino = { amount = 22 },
    cappuccino = { amount = 20 },
    milk = { amount = 12 },
    --Tea 
    tea_bubble_green = { amount = 15 },
	tea_bubble_pink = { amount = 16 },
	tea_bubble_blue = { amount = 17 },
	tea_bubble_orange = { amount = 18 },
	matchauwutea = { amount = 19 },
	tea_bubble = { amount = 15 },
	lemonnlimeicedtea = { amount = 16 },
	peachicedtea = { amount = 17 },
	strawberryuwutea = { amount = 18 },
	uwu_btea = { amount = 19 },
	uwububbletearose = { amount = 18 },
	uwububbleteamint = { amount = 17 },
	uwububbleteablueberry = { amount = 16 },
	iced_black_tea_lemonade = { amount = 15 },
	green_tea_lemonade = { amount = 19 },

    --Cakes & Desserts
	kittycupcake = { amount = 12 },
	cake_strawberry = { amount = 14 },
	cupcake = { amount = 15 },
	cupcake2 = { amount = 14 },
	cupcake_blue = { amount = 11 },
	cupcake_vanilla = { amount = 12 },
	cake_slice4 = { amount = 10 },
	cake_slice3 = { amount = 15 },
	cake_slice2 = { amount = 14 },
	cake_slice1 = { amount = 13 },
	cake = { amount = 12 },
	cake_carrot = { amount = 10 },

    -- Light food and snacks
    bread = { amount = 15 },
    sandwich = { amount = 19 },
	steak_and_cheese = { amount = 22 },
	steakncheese = { amount = 12 },
    bagel = { amount = 22 },
    donut = { amount = 16 },
    casino_donut = { amount = 22 },
    catdonut = { amount = 18 },
    cb_donut = { amount = 20 },
    donut1 = { amount = 21 },
    donut2 = { amount = 22 },
    donut3 = { amount = 23 },
    donut4 = { amount = 24 },
    donut6 = { amount = 26 },
    donut7 = { amount = 27 },
    donut8 = { amount = 28 },
    chocdonut = { amount = 25 },
    chips = { amount = 15 },
    fishsticks = { amount = 20 },
    sweetcorn = { amount = 14 },
    seafood = { amount = 24 },
    flour = { amount = 5 },
    mayo = { amount = 5 },
    mustard = { amount = 5 },

    -- Plates of food / big meals (strong relief)
    hamburger = { amount = 45 },
	steakburger = { amount = 55 },
	pizza = { amount = 45 },
	pizza_ham = { amount = 65 },
    hotdog = { amount = 30 },
    hotdog_plain = { amount = 30 },
    hotdog_chili = { amount = 40 },
    hotdog_taco = { amount = 35 },
    hotdog_veggie = { amount = 20 },
    hotdog_chillicheesedog = { amount = 50 },
    hotdog_deluxe = { amount = 55 },
    hotdog_mustard = { amount = 52 },
    hotdog_ketchup = { amount = 45 },
    taco = { amount = 45 },
    fries = { amount = 35 },
    turkey_leg = { amount = 50 },
    hot_chicken_wrap = { amount = 45 },
    kira_kira_currye = { amount = 55 },

    -- Fruit (healthy, moderate relief)
    orange = { amount = 15 },
    orange_big = { amount = 20 },
    kiwi = { amount = 15 },
    pineapple = { amount = 18 },
    grape = { amount = 18 },
	red_grapes = { amount = 19 },
	white_grapes = { amount = 20 },
    peach = { amount = 15 },
    pear = { amount = 15 },
    apple_green = { amount = 12 },
    apple_red = { amount = 12 },
    banana = { amount = 18 },
    vine = { amount = 12 },

    -- Beers (good relief)
    beer_box = { amount = 30 },
    beer_pisswaser4 = { amount = 35 },
    beer_pisswaser3 = { amount = 35 },
    beer_pisswaser2 = { amount = 35 },
    beer_pisswaser = { amount = 30 },
    beer_logger = { amount = 40 },
    beer_dusche = { amount = 40 },
    beer_ambeer = { amount = 40 },
    beer_50cl = { amount = 45 },

    -- Strong alcohol and cocktails (very strong relief)
    whiskey = { amount = 70 },
    rhum = { amount = 65 },
    vodka = { amount = 70 },
    tequila = { amount = 70 },
    rare_tequila = { amount = 80 },
    red_wine = { amount = 45 },
    white_wine = { amount = 45 },
    rose_wine = { amount = 45 },
    champ = { amount = 55 },
    grand_cru = { amount = 60 },
    cosmopolitan = { amount = 65 },
    cubalibre = { amount = 65 },
    rhumcoca = { amount = 65 },
    rhumfruit = { amount = 70 },
    sexonthebeach = { amount = 60 },
    virgin = { amount = 45 },

    -- Shakes and sweets
    chocolate_shake = { amount = 30 },
    chocolate_cookie_shake = { amount = 32 },
    cookie_shake = { amount = 28 },
    strawberry_shake = { amount = 30 },
    vanilla_shake = { amount = 28 },

    chocolate_chunk_brownie = { amount = 32 },
    chocolate_chunk_cookie = { amount = 28 },
    chocolate_fudge_brownie = { amount = 35 },
    churros_dip = { amount = 30 },

    cig_pack = { amount = 10 },

    -- Nicotine pouch: full clear
    nicotine_pouch = { amount = 0 }
}
