# Convert qb-core shared/items.lua (QBShared.Items) entries to ox_inventory item tables.
# Skips type == 'weapon'. Source: https://github.com/qbcore-framework/qb-core/blob/main/shared/items.lua
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QB_PATH = ROOT / "qb_items_raw.lua"
OUT_PATH = ROOT / "resources" / "ox_inventory" / "data" / "items_from_qb.lua"

# One-line QB item: key = { name = 'x', label = 'y', weight = N, type = 'item', ...
LINE_RE = re.compile(
    r"^\s*([a-zA-Z0-9_]+)\s*=\s*\{(.+)\},\s*$"
)


def parse_qb_fields(inner: str) -> dict | None:
    if "type = 'weapon'" in inner or 'type = "weapon"' in inner:
        return None
    if "type = 'item'" not in inner and 'type = "item"' not in inner:
        return None
    out = {}
    for key in ("name", "label", "image", "description"):
        m = re.search(rf"{key}\s*=\s*'((?:\\'|[^'])*)'", inner)
        if m:
            out[key] = m.group(1).replace("\\'", "'")
    m = re.search(r"weight\s*=\s*(\d+)", inner)
    if m:
        out["weight"] = int(m.group(1))
    m = re.search(r"unique\s*=\s*(true|false)", inner)
    out["unique"] = m and m.group(1) == "true"
    if "name" not in out or "label" not in out:
        return None
    return out


def lua_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def to_ox_lua(d: dict) -> str:
    name = d["name"]
    label = d["label"]
    weight = d.get("weight", 100)
    stack = "false" if d.get("unique") else "true"
    desc = d.get("description", "")
    image = d.get("image", "").replace(".png", "").replace(".PNG", "")
    lines = [
        f"\t['{name}'] = {{",
        f"\t\tlabel = '{lua_escape(label)}',",
        f"\t\tweight = {weight},",
        f"\t\tstack = {stack},",
    ]
    if desc:
        lines.append(f"\t\tdescription = '{lua_escape(desc)}',")
    if image:
        lines.append(f"\t\tclient = {{ image = '{lua_escape(image)}.png' }},")
    lines.append("\t},")
    return "\n".join(lines)


def main() -> int:
    if not QB_PATH.is_file():
        print("Missing qb_items_raw.lua — download qb-core shared/items.lua to repo root.", file=sys.stderr)
        return 1
    text = QB_PATH.read_text(encoding="utf-8")
    blocks = []
    for line in text.splitlines():
        m = LINE_RE.match(line)
        if not m:
            continue
        inner = m.group(2)
        fields = parse_qb_fields(inner)
        if not fields:
            continue
        blocks.append(to_ox_lua(fields))
    header = (
        "-- AUTO-GENERATED by tools/qb_to_ox_items.py from qb-core shared/items.lua\n"
        "-- Non-weapon `item` rows only. Do not edit by hand; regenerate after updating qb_items_raw.lua.\n"
        "return {\n"
    )
    footer = "}\n"
    OUT_PATH.write_text(header + "\n".join(blocks) + "\n" + footer, encoding="utf-8")
    print(f"Wrote {len(blocks)} items to {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
