/**
 * Convert qb-core shared/items.lua (QBShared.Items) to ox_inventory item chunk.
 * Skips type === 'weapon'. Source: qbcore-framework/qb-core shared/items.lua
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const QB_PATH = path.join(ROOT, 'qb_items_raw.lua');
const OUT_PATH = path.join(ROOT, 'resources', 'ox_inventory', 'data', 'items_from_qb.lua');

const LINE_RE = /^\s*([a-zA-Z0-9_]+)\s*=\s*\{(.+)\},\s*$/;

function parseFields(inner) {
  if (/type\s*=\s*['"]weapon['"]/.test(inner)) return null;
  if (!/type\s*=\s*['"]item['"]/.test(inner)) return null;
  const getStr = (key) => {
    const m = inner.match(new RegExp(`${key}\\s*=\\s*'((?:\\\\'|[^'])*)'`));
    return m ? m[1].replace(/\\'/g, "'") : null;
  };
  const getStrDq = (key) => {
    const m = inner.match(new RegExp(`${key}\\s*=\\s*"((?:\\\\"|[^"])*)"`));
    return m ? m[1].replace(/\\"/g, '"') : null;
  };
  const name = getStr('name') || getStrDq('name');
  const label = getStr('label') || getStrDq('label');
  if (!name || !label) return null;
  const wm = inner.match(/weight\s*=\s*(\d+)/);
  const weight = wm ? parseInt(wm[1], 10) : 100;
  const unique = /unique\s*=\s*true/.test(inner);
  const desc = getStr('description') || getStrDq('description') || '';
  let image = getStr('image') || getStrDq('image') || '';
  image = image.replace(/\.png$/i, '');
  return { name, label, weight, unique, description: desc, image };
}

function luaEsc(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function toOxLua(d) {
  const stack = d.unique ? 'false' : 'true';
  const lines = [
    `\t['${d.name}'] = {`,
    `\t\tlabel = '${luaEsc(d.label)}',`,
    `\t\tweight = ${d.weight},`,
    `\t\tstack = ${stack},`,
  ];
  if (d.description) lines.push(`\t\tdescription = '${luaEsc(d.description)}',`);
  if (d.image) lines.push(`\t\tclient = { image = '${luaEsc(d.image)}.png' },`);
  lines.push('\t},');
  return lines.join('\n');
}

const text = fs.readFileSync(QB_PATH, 'utf8');
const blocks = [];
for (const line of text.split(/\r?\n/)) {
  const m = line.match(LINE_RE);
  if (!m) continue;
  const fields = parseFields(m[2]);
  if (!fields) continue;
  blocks.push(toOxLua(fields));
}

const header = `-- AUTO-GENERATED by tools/qb_to_ox_items.mjs from qb-core shared/items.lua (non-weapon items only).
-- Regenerate: place qb_items_raw.lua in repo root, run: node tools/qb_to_ox_items.mjs
return {
`;

const footer = `}
`;

fs.writeFileSync(OUT_PATH, header + blocks.join('\n') + '\n' + footer, 'utf8');
console.log(`Wrote ${blocks.length} items to ${OUT_PATH}`);
